# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [4]:
#code here
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

reshaped = original.reshape(3, 4)

print("Original  : " , original)

print("\nReshaped :  \n" , reshaped)


Original  :  [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped :  
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
array1 = np.array([[1, 2, 3],[4, 5, 6]])

array2 = np.array([[7, 8, 9],[10, 11, 12]])

horizontal = np.concatenate((array1, array2), axis=1)
print("Horizontal : \n",horizontal,"\n\n")

vertical = np.concatenate((array1, array2), axis=0)
print("Verticle : \n",vertical)

Horizontal : 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 


Verticle : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [10]:
#code here
def classify_email(x):
    imp_k = ["urgent", "important", "priority", "critical"]
    pro_k = ["sale", "discount", "offer", "promo", "deal"]
    spam_k = ["win", "free", "prize", "lottery", "viagra"]

    imp = []
    pro = []
    spam = []

    for email_content in x:
        lower_content = email_content.lower()

        # Check for importance
        if any(keyword in lower_content for keyword in imp_k):
            imp.append(email_content)

        # Check for promotions/deals
        elif any(keyword in lower_content for keyword in pro_k):
            pro.append(email_content)

        # Check for spam
        elif any(keyword in lower_content for keyword in spam_k):
            spam.append(email_content)

    return imp, pro, spam

# Example usage
emails = ["URGENT: Your attention is needed regarding an important matter!","Get 50% off on your next purchase!","You've won a free vacation! Claim your prize now.","Meeting tomorrow at 10 AM."]

important_emails, promotions_emails, spam_emails = classify_email(emails)

print("Important Emails:")
print(important_emails)

print("\nPromotions Emails:")
print(promotions_emails)

print("\nSpam Emails:")
print(spam_emails)



Important Emails:
['URGENT: Your attention is needed regarding an important matter!']

Promotions Emails:
[]

Spam Emails:
["You've won a free vacation! Claim your prize now."]


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [12]:
#code here
english_to_spanish = {"hello": "hola","goodbye": "adiós","thank you": "gracias","yes": "sí","no": "no","cat": "gato","dog": "perro","book": "libro","computer": "computadora","water": "agua"}

while True:

  x = input("enter the Word : ")

  if x == 'q':
    break

  elif x in english_to_spanish:
    print("Translation : ",english_to_spanish[x])
  else:
    print("Word not found ! Try again")




enter the Word : oye
Word not found ! Try again
enter the Word : q


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [21]:
import pandas as pd

x = pd.read_csv('/content/data.csv')

x.loc[x['Global_Sales'].idxmax()]['Genre']


'Sports'

In [23]:
print(x['NA_Sales'].mean())
print(x['EU_Sales'].mean())
print(x['JP_Sales'].mean())
print(x['NA_Sales'].mean())

0.26466742981082064
0.14665200626581515
0.077781660441017
0.26466742981082064


In [25]:
x.sort_values(by='Global_Sales', ascending=False)['Genre'].head(5)


0          Sports
1        Platform
2          Racing
3          Sports
4    Role-Playing
Name: Genre, dtype: object

In [34]:
x.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()


NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

In [36]:
x.loc[x['NA_Sales'].idxmax()]['Genre']

'Sports'

In [26]:
x.tail()

Rank                                              Name Platform  \
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year     Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
16593  2002.0  Platform       Kemco      0.01      0.00       0.0   
16594  2003.0   Shooter  Infogrames      0.01      0.00       0.0   
16595  2008.0    Racing  Activision      0.00      0.00       0.0   
16596  2010.0    Puzzle    7G//AMES      0.00      0.01       0.0   
16597  2003.0  Platform     Wanadoo      0.01      0.00       0.0   

       Other_Sales  Global_Sales  
16593          0.0          0.01  
16594          0.0          0.01  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01

In [28]:
x.sort_values(by='Global_Sales' ,  ascending=False)['Platform'].head(3)

0    Wii
1    NES
2    Wii
Name: Platform, dtype: object

In [31]:
total = x['Global_Sales'].sum()

# Group by genre and calculate market share for each genre category
market_share = x.groupby('Genre')['Global_Sales'].sum() / total * 100

print("Market Share for Each Genre Category:")
print(market_share)

Market Share for Each Genre Category:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [32]:
correlation_coefficient = x['NA_Sales'].corr(x['EU_Sales'])

print("Correlation Coefficient between NA_Sales and EU_Sales:", correlation_coefficient)

Correlation Coefficient between NA_Sales and EU_Sales: 0.7677267483702631


Some tree example

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
